### PR TITLE
Fixes issue #93

### PR DESCRIPTION
**Pull request by Avinandan22**
Fixes issue #93

### CODE REVIEW

**Comment by avik-pal** [comment]
@Avinandan22 could you make the same changes in the remaining examples as well?

**Comment by avik-pal** [comment]
@Avinandan22  The changes look fine. Can you still rerun the notebooks locally to confirm everything is working?

**Comment by Avinandan22** [comment]
Made changes for Adversarial Autoencoders and Custom Losses, the other 2 do not use MNIST so did not make any changes.

**Comment by Avinandan22** [comment]
Ran them. Working correctly now.

**Comment by avik-pal** [comment]
Thanks @Avinandan22

**Pull request merged**
